### PR TITLE
Fix #537, commit and format check doesn't execute when PR title format fails

### LINKED ISSUE #537: Commit and format check doesn't execute when PR title format fails
**Is your feature request related to a problem? Please describe.**
When running against a pull request, if the PRs title fails the format check, the workflow skips the commit message check. 

**Describe the solution you'd like**
Workflow checks both PR and commit titles regardless of failures

**Describe alternatives you've considered**
- Separate into parallel jobs. 
- Use a "keep going on failure" flag for the step (not sure if this is an option)

**Additional context**
See https://github.com/nasa/cFE/actions/runs/2414940003

**Requester Info**
Gerardo E. Cruz-Ortiz, NASA

### PR DESCRIPTION
**Pull request by paulober**
Fixes nasa/cFS#537 with continue-on-error solution.

**Checklist (Please check before submitting)**

* [x] I reviewed the [Contributing Guide](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md).
* [x] I signed and emailed the appropriate [Contributor License Agreement](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) to GSFC-SoftwareRelease@mail.nasa.gov and copied cfs-program@lists.nasa.gov.

**Describe the contribution**
A clear and concise description of what the contribution is.
- Fixes nasa/cFS#537

**Expected behavior changes**
A clear and concise description of how this contribution will change behavior and level of impact.
 - The action continues even if title format check failes

**Code contributions**
The cFS repository is provided to bundle the cFS Framework.  It is utilized for bundling submodules, continuous integration testing, and version management and does not contain any software.  Code contributions should be directed to the appropriate submodule.

**Contributor Info - All information REQUIRED for consideration of pull request**
Personal

### CODE REVIEW

**Review by astrogeco — APPROVED** [review]

**Comment by astrogeco** [comment]
@paulober does this still show a failed check for the commit and title job?

**Review by skliper — APPROVED** [review]

**Comment by paulober** [comment]
> @paulober does this still show a failed check for the commit and title job?

good that you mentioned that. "continue-on-error" would not mark the workflow as failed no matter what the step results. So I replaced the "continue-on-error" solution with, so to speak, "run-if", which runs the second step ("check commit message") even if the first step threw an error. This solution now lets the job fail if one of the two steps fails but still it always runs both.

**Comment by dzbaker** [comment]
@paulober I moved the issue to cFS, now it's #537. Would you be able to amend the commit message to reference the new issue number?

**Comment by paulober** [comment]
> @paulober I moved the issue to cFS, now it's #537. Would you be able to amend the commit message to reference the new issue number?

Done

**Comment by dzbaker** [comment]
CCB 8 September 2022: Need to update commit message to indicate that it is fixing the format check for CI.

**Comment by paulober** [comment]
> CCB 8 September 2022: Need to update commit message to indicate that it is fixing the format check for CI.

Done and rebased feature branch.

**Pull request merged**
