### PR TITLE
cFS Bundle Integration Candidate: 2021-01-12

### PR DESCRIPTION
**Pull request by astrogeco**
**Describe the contribution**

Combines
- <https://github.com/nasa/cfe/issues/1088>
- <https://github.com/nasa/osal/issues/750>
- <https://github.com/nasa/psp/issues/240>

**Testing performed**
See <https://github.com/nasa/cFS/pull/174/checks>

**Expected behavior changes**
See submodule PRs

**System(s) tested on**
Ubuntu 18.04

**Additional context**
None

**Code contibutions**
The cFS repository is provided to bundle the cFS Framework.  It is utilized for bundling submodules, continuous integration testing, and version management and does not contain any software.  Code contributions should be directed to the appropriate submodule.

**Contributor Info - All information REQUIRED for consideration of pull request**
@skliper 
@jphickey 
@zanzaben 
@CDKnightNASA

### CODE REVIEW

**Comment by astrogeco** [comment]
@skliper @jphickey still have `57: select-test` hanging, Wasn't this fixed by <https://github.com/nasa/osal/pull/721>?

**Comment by skliper** [comment]
@astrogeco it should have, maybe there is another issue...

**Comment by skliper** [comment]
> @skliper @jphickey still have `57: select-test` hanging. See https://github.com/nasa/cFS/pull/174/checks?check_run_id=1689399944
> 
> Wasn't this fixed by [nasa/osal#721](https://github.com/nasa/osal/pull/721)?

@zanzaben - could you prioritize looking into this?

**Comment by zanzaben** [comment]
> @skliper @jphickey still have `57: select-test` hanging. See https://github.com/nasa/cFS/pull/174/checks?check_run_id=1689399944
> 
> Wasn't this fixed by [nasa/osal#721](https://github.com/nasa/osal/pull/721)?

How often did it happen?

**Comment by astrogeco** [comment]
> > @skliper @jphickey still have `57: select-test` hanging. See https://github.com/nasa/cFS/pull/174/checks?check_run_id=1689399944
> > Wasn't this fixed by [nasa/osal#721](https://github.com/nasa/osal/pull/721)?
> 
> How often did it happen?

Here is another instance
https://github.com/nasa/cFS/runs/1690379753?check_suite_focus=true

**Comment by astrogeco** [comment]
And one more
https://github.com/nasa/cFS/pull/174/checks?check_run_id=1690641558

**Comment by zanzaben** [comment]
> And one more
> https://github.com/nasa/cFS/pull/174/checks?check_run_id=1690641558

Thank you, I understand the issue now and am working on a fix.

**Comment by skliper** [comment]
I recommend merging in the PR as a hotfix so it gets exercised this round if possible.

**Comment by astrogeco** [comment]
> I recommend merging in the PR as a hotfix so it gets exercised this round if possible.

Adding information for completeness, 

Issue: nasa/osal#755 "resolve subtasks not ending on time " 

and 

PR: nasa/osal#756

**Pull request merged**
