### PR TITLE
Fix #39, Improve CI testing

### LINKED ISSUE #39: Improve Travis CI testing
**Is your feature request related to a problem? Please describe.**
Travis CI currently just does cppcheck and default build on the bundle

**Describe the solution you'd like**
Parallel test the following:
- BUILDTYPE=release OMIT_DEPRECATED=true STRICT_NO_WARNINGS=true
- BUILDTYPE=release OMIT_DEPRECATED=false(default) STRICT_NO_WARNINGS=true
- BUILDTYPE=debug(default) OMIT_DEPRECATED=true STRICT_NO_WARNINGS=true
- BUILDTYPE=debug(default) OMIT_DEPRECATED=false(default) STRICT_NO_WARNINGS=true

And do the following tests:
- Add document generation (eventually enforce no warnings)
  - make doc
  - make usersguide
  - make osalguide (dependent on https://github.com/nasa/cFE/pull/446)
- Build with ENABLE_UNIT_TESTS=TRUE SIMULATION=native
- Run unit tests (eventually enforce coverage)
- Execute cFE and pipe output to file
- Send reset cmd from cmdutil
- Confirm execution output lacks error/warning/fail messages

**Describe alternatives you've considered**
None

**Additional context**
Eventually add nightly or triggered local builds for other environments (pc-RTEMS, vxworks on a modern platform)
Eventually add automated build verification (trade CI vs local)

**Requester Info**
Jacob Hageman - NASA/GSFC

### PR DESCRIPTION
**Pull request by skliper**
**Describe the contribution**
Fixes #39 

**Testing performed**
See CI results

**Expected behavior changes**
Better CI testing coverage

**System(s) tested on**
CI

**Additional context**
Jobs will fail until issues are resolved.

**Contributor Info**
Jacob Hageman - NASA/GSFC

### CODE REVIEW

**Comment by skliper** [comment]
> This type of hack isn't necessary - just create a file `native_osconfig.h` that contains the overrides (in this case just `#define OSAL_DEBUG_PERMISSIVE_MODE`) and it will get pulled in when building with SIMULATION=native.

I'd prefer to avoid duplicating all the settings in osconfig.h in a native_osconfig.h, is that what this would mean?  I'd much rather just change the setting needed for CI, which is what this does.

**Comment by skliper** [comment]
Note we've got an open ticket for PERMISSIVE/native "nicer" behavior.  This would be my preferred solution.

**Comment by jphickey** [comment]
> I'd prefer to avoid duplicating all the settings in osconfig.h in a native_osconfig.h, is that what this would mean? I'd much rather just change the setting needed for CI, which is what this does.

No - both files are used.  The `default_osconfig.h` file provides the basis config, and the `native_osconfig.h` only has the additional platform-specific options.  It only needs to have the one line:

`#define OSAL_DEBUG_PERMISSIVE_MODE`

**Comment by skliper** [comment]
> > I'd prefer to avoid duplicating all the settings in osconfig.h in a native_osconfig.h, is that what this would mean? I'd much rather just change the setting needed for CI, which is what this does.
> 
> No - both files are used. The `default_osconfig.h` file provides the basis config, and the `native_osconfig.h` only has the additional platform-specific options. It only needs to have the one line:
> 
> `#define OSAL_DEBUG_PERMISSIVE_MODE`

Is that the preferred solution to making SIMULATION=native use permissive mode (related to https://github.com/nasa/cFE/issues/358)?  If so then it sounds good to me.

**Comment by skliper** [comment]
Note this depends on https://github.com/nasa/cFE/pull/479, https://github.com/nasa/cFE/pull/463, https://github.com/nasa/cFE/pull/462 and some jobs will fail until warnings/issues are fixed.

**Comment by skliper** [comment]
See also https://github.com/nasa/cFE/issues/358 for PERMISSIVE mode when SIMULATION=native

**Comment by skliper** [comment]
CCB 20200115 - discussed and presented tests.  This pull will require special handling, since some tests in the matrix will break.  Suggest rebasing this on top of IC branches until fixed (and to identify latest errors).

**Comment by skliper** [comment]
Current issues: 
- nasa/cFE#487
- https://github.com/nasa/sample_app/issues/35
- https://github.com/nasa/cFE/issues/489

**Comment by skliper** [comment]
Rebased on latest master (after ic 20200121 merge)

**Comment by skliper** [comment]
Once https://github.com/nasa/cFE/pull/505/files is merged, can remove the sed "hack".

**Comment by skliper** [comment]
All PASSED!!! Let's get this checked in asap!!

**Comment by astrogeco** [comment]
CCB 20200318 - Approved.

**Pull request merged**
