### PR TITLE
cFS-Bundle Integration Candidate:2021-08-10

### LINKED ISSUE #322: Add Discussions in Contributing Guide
**Checklist (Please check before submitting)**

* [x] I reviewed the [Contributing Guide](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md).
* [x] I reviewed the [cFS README.md file](https://github.com/nasa/cFS/blob/main/README.md) to see if the feature is in the major future work.
* [x] I performed a cursory search to see if the feature request is relevant, not redundant, nor in conflict with other tickets.

**Is your feature request related to a problem? Please describe.**
cFS now uses Discussions as a way to ask questions or request information. This is not in the contributing guide. 

**Describe the solution you'd like**
Add that users may start discussions or ask questions in the Discussions tab of cFS under Ways to Contribute in the Contributing Guide. 

**Requester Info**
Ariel Adams, ASRC Federal

### LINKED ISSUE #331: Skip documentation deploy job instead of step when not pushing to main
**Checklist (Please check before submitting)**

* [x] I reviewed the [Contributing Guide](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md).
* [x] I reviewed the [cFS README.md file](https://github.com/nasa/cFS/blob/main/README.md) to see if the feature is in the major future work.
* [x] I performed a cursory search to see if the feature request is relevant, not redundant, nor in conflict with other tickets.

**Is your feature request related to a problem? Please describe.**
The deploy jobs in the documentation workflow run even when the criteria for deployment are not met. This is not a problem since the git push step, which does the actual deployment does not run. 

However, this does spin up an extra VM that then gets shut down immediately. Skipping the job can shave a couple of seconds from the full CI suite.

https://github.com/nasa/cFS/blob/4ad06770be5d725037699f3f4ec44e5f5752022e/.github/workflows/build-documentation.yml#L271

**Describe the solution you'd like**
Move the if condition up one level from the deploy _step_ to the deploy **job**. 

**Describe alternatives you've considered**
Leave as is.

**Additional context**
None

**Requester Info**
Full name and company/organization if applicable

### PR DESCRIPTION
**Pull request by astrogeco**
**Checklist (Please check before submitting)**

* [x] I reviewed the [Contributing Guide](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md).
* [x] I signed and emailed the appropriate Contributor License agreement to GSFC-SoftwareRelease@mail.nasa.gov and copied cfs-program@lists.nasa.gov.

**Describe the contribution**

PR #332
- Fix #331, Skip deploy job instead of step 

PR #323 
- Fix #322, Add Discussions in the Contributing Guide 

**Also Combines**

- nasa/cFE#1772, v6.8.0-rc1+dev844
- nasa/osal#1127, v5.1.0-rc1+dev590

**Includes**

*cFE*

- nasa/cFE#1737, Move global count into test global struct.
- nasa/cFE#1722, Add ES application control API functional tests
- nasa/cFE#1744, update coverage test to use UtAssert macros 
- nasa/cFE#1734, Add table api functional tests
- nasa/cfe#1753, Add Generic Counter API test
- nasa/cFE#1716, Add resource ID API functional tests
- nasa/cFE#1766, Finish ES misc API functional test 
- nasa/cFE#1764, Last char truncated in coverage log output 
- nasa/cFE#1728, Mistakes in some copyright headers
- nasa/cFE#1767, Add misc time api functional test cFE
- nasa/cFE#1749, Add Functional Test for EVS Reset Filters API
- nasa/cFE#1796, replace VOIDCALL assert macro 
- nasa/cFE#1781, RTEMS CFE_FT_Global build failure

*osal* 

- nasa/osal#1117, Add absolute branch coverage check 

**Testing performed**

cFE Checks <https://github.com/nasa/cFE/pull/1772/checks>
cFS Checks <https://github.com/nasa/cFS/pull/333/checks>
osal Checks <https://github.com/nasa/osal/pull/1127/checks>

**Expected behavior changes**
See PRs

**System(s) tested on**

CI 

Ubuntu 18.04
RTEMS 4.11 (qemu)
RTEMS 5.0 (qemu)

**Additional context**
None

**Contributor Info - All information REQUIRED for consideration of pull request**

@jphickey
@zanzaben
@nmullane
@pavll
@astrogeco 
@ArielSAdamsNASA

### CODE REVIEW

**Comment by astrogeco** [comment]
@nmullane, @zanzaben looks like the test app isn't compiling isn't compiling on RTEMS

**Comment by zanzaben** [comment]
> @nmullane, @zanzaben looks like the test app isn't compiling isn't compiling on RTEMS

@jphickey thoughts?

**Comment by zanzaben** [comment]
@nmullane your CFE_FT_Global changes are conflicting with https://github.com/nasa/cFE/pull/1737

**Comment by astrogeco** [comment]
> @nmullane your CFE_FT_Global changes are conflicting with [nasa/cFE#1737](https://github.com/nasa/cFE/pull/1737)

weird I thought I resolved them, and they seemed to work on Linux
https://github.com/nasa/cFE/pull/1734/commits

**Comment by nmullane** [comment]
> @nmullane your CFE_FT_Global changes are conflicting with [nasa/cFE#1737](https://github.com/nasa/cFE/pull/1737)

I didn't think my table api functional tests were going to be included in this integration candidate, so I was waiting for https://github.com/nasa/cFE/pull/1737 to be merged before updating my pr for the CCB this week.

**Comment by astrogeco** [comment]
my bad you all, this is what happens when I skip a couple of tagups :)

**Comment by astrogeco** [comment]
So looking at this more closely, only debug mode fails in Linux

**Comment by astrogeco** [comment]
@zanzaben I don't think this is an actual conflict, wouldn't it fail to build on Linux if it were?

**Pull request merged**
