### PR TITLE
Fix #59, Exclude LGTM False Positives

### LINKED ISSUE #59: Exclude lgtm false positives
**Is your feature request related to a problem? Please describe.**
sample_lib triggers a lgtm error based on checking strncpy return (false alarm)

**Describe the solution you'd like**
Exclude string-copy-return-value-as-boolean (triggered by sample_lib, which is doing this on purpose)

**Describe alternatives you've considered**
Could clutter code to exclude this specific call from triggering the warning.

**Additional context**
None

**Requester Info**
Jacob Hageman - NASA/GSFC

### PR DESCRIPTION
**Pull request by ArielSAdamsNASA**
**Checklist (Please check before submitting)**

* [x] I reviewed the [Contributing Guide](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md).
* [ ] I signed and emailed the appropriate Contributor License agreement to GSFC-SoftwareRelease@mail.nasa.gov and copied cfs-program@lists.nasa.gov.

**Describe the contribution**
Fixes #59 
Excludes cpp/string-copy-return-value-as-boolean

**Testing performed**
None 

**Expected behavior changes**
No longer run against string-copy-return-value-as-boolean

**Contributor Info - All information REQUIRED for consideration of pull request**
Ariel Adams, ASRC Federal

### CODE REVIEW

**Comment by astrogeco** [comment]
Do we want to exclude this for the whole analysis or just for sample_app? Also, is there a good way to maintain the github actions configuration aligned with the lgtm one?

**Comment by ArielSAdamsNASA** [comment]
> Also, is there a good way to maintain the github actions configuration aligned with the lgtm one?

https://github.com/github/codeql/issues/6314

Thoughts?

**Comment by astrogeco** [comment]
Consider, pending and fixing directly in sample_app and sample_lib
https://lgtm.com/projects/g/nasa/cFS/alerts/?mode=tree&severity=error&ruleFocus=1507228686331

**Comment by ArielSAdamsNASA** [comment]
Closed: No longer using LGTM

**Pull request closed without merging**
