### PR TITLE
Integration Candidate 2020-04-01

### PR DESCRIPTION
**Pull request by astrogeco**
**Describe the contribution**
Integration Candidate
Integrates:

1. cFE 6.7.12 - https://github.com/nasa/cFE/pull/586
2. osal 5.0.11 - https://github.com/nasa/OSAL/pull/408
3. psp 1.4.8 - https://github.com/nasa/PSP/pull/151
4. cFS-GroundSystem 2.1.6 - https://github.com/nasa/cFS-GroundSystem/pull/69

**Testing performed**
Bundle CI - https://travis-ci.com/github/nasa/cFS/builds/159710339

**Expected behavior changes**
See PRs

**System(s) tested on**
Bundle CI - Ubuntu:Bionic

**Contributor Info - All information REQUIRED for consideration of pull request**
Gerardo E. Cruz-Ortiz, NASA-GSFC

### CODE REVIEW

**Comment by astrogeco** [comment]
@skliper I think the deprecated `OS_IntLock` and `OS_IntUnlock` are causing trouble in `cfe_es_perf.c`

**Comment by skliper** [comment]
See the comment on https://github.com/nasa/osal/pull/396

This won't compile with deprecated removed until https://github.com/nasa/cfe/issues/456 gets resolved

**Comment by astrogeco** [comment]
@skliper I made two commits in my cFE fork that I think fix this but I worry that it might break something else:

https://github.com/astrogeco/cFE/commit/8da0e475ada89ab041f48a1a040ab19b20388b80
https://github.com/astrogeco/cFE/commit/bb2a40176a768f348b8ff58ded8a8e9d0788af0f

**Comment by jphickey** [comment]
Note that the pull request for nasa/cfe#456 is now submitted in nasa/cfe#595, and this will cause a merge conflict with the `#ifdef` blocks where currently it is a clean merge.

Should be an easy rebase though, so if you do put this in let me know so I can rebase the pull request.

**Comment by astrogeco** [comment]
> Note that the pull request for [nasa/cFE#456](https://github.com/nasa/cFE/issues/456) is now submitted in [nasa/cFE#595](https://github.com/nasa/cFE/pull/595), and this will cause a merge conflict with the `#ifdef` blocks where currently it is a clean merge.
> 
> Should be an easy rebase though, so if you do put this in let me know so I can rebase the pull request.

I think a better option is to fast-track https://github.com/nasa/cFE/pull/595 and merge that instead @skliper thoughts?

**Comment by skliper** [comment]
I'm all for moving https://github.com/nasa/cFE/pull/595 forward.  I already approved.

**Comment by jphickey** [comment]
I've got another pull request that I'm just about to submit for 295/480 which depends on 595, so if you decide to include nasa/CFE#595, then let me know as soon as the integration candidate is ready so I can rebase to it.

**Comment by astrogeco** [comment]
> I've got another pull request that I'm just about to submit for 295/480 which depends on 595, so if you decide to include [nasa/cFE#595](https://github.com/nasa/cFE/pull/595), then let me know as soon as the integration candidate is ready so I can rebase to it.

@jphickey, I just merged the IC.

**Pull request merged**
