### PR TITLE
Fix #338, Add MISRA Addons for cppcheck

### LINKED ISSUE #338: MISRA Addon for cppcheck static analysis
**Checklist (Please check before submitting)**

* [x] I reviewed the [Contributing Guide](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md).
* [x] I reviewed the [cFS README.md file](https://github.com/nasa/cFS/blob/main/README.md) to see if the feature is in the major future work.
* [x] I performed a cursory search to see if the feature request is relevant, not redundant, nor in conflict with other tickets.

**Is your feature request related to a problem? Please describe.**
Currently the cppcheck static analysis workflow does not include MISRA addons. Adding the MISRA addons allows for a more thorough static analysis check.

**Describe the solution you'd like**
Using the cppcheck addon for MISRA, the current workflow has been modified to include the MISRA addons. 

**Describe alternatives you've considered**
Alternatives might be a separate MISRA check workflow, but this way is more consolidated and easier.

**Additional context**
The cppcheck addon used can be found here: https://github.com/danmar/cppcheck/blob/main/addons/README.md
The MISRA Python addon is here: https://github.com/danmar/cppcheck/blob/main/addons/misra.py

**Requester Info**
Adrian Schalk
m225766@usna.edu
Goddard summer Intern under Ariel Adams
Midshipman, USN, US Naval Academy

### PR DESCRIPTION
**Pull request by ArielSAdamsNASA**
**Checklist (Please check before submitting)**

* [x] I reviewed the [Contributing Guide](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md).
* [ ] I signed and emailed the appropriate Contributor License agreement to GSFC-SoftwareRelease@mail.nasa.gov and copied cfs-program@lists.nasa.gov.

**Describe the contribution**
Fixes #338 

**Testing performed**
Tested on forked repo: https://github.com/ArielSAdamsNASA/cFS-JSF-Rules/actions/runs/1143235812

image

**Expected behavior changes**
Runs MISRA rules for bundle, cfe, osal, and psp. Has a job for regular "clean" cppcheck and misra cppcheck.

**Additional context**
Future work includes:
- [x] Running MISRA rules for the bundle, cfe, osal, and psp. 
- [x] Showing errors in the check for errors step

**Contributor Info - All information REQUIRED for consideration of pull request**
Ariel Adams, ASRC Federal

### CODE REVIEW

**Review by skliper — CHANGES_REQUESTED** [review]
I don't think we are allowed to publish MISRA rules, also it looks like the check is just running against misra-test.c.  I recommend starting with a local report and doing some analysis there prior to pushing it into CI...

**Comment by ArielSAdamsNASA** [comment]
> I don't think we are allowed to publish MISRA rules, also it looks like the check is just running against misra-test.c. I recommend starting with a local report and doing some analysis there prior to pushing it into CI...

@skliper See new changes. Created a separate job for misra rules. Ran misra analysis against bundle, cfe, osal, and psp instead of misra-test.c.

**Comment by skliper** [comment]
It's great work, I'm just concerned it may be a little premature to put into CI to run on every push from a project management perspective since we don't really have a plan in place with what to do with the actual results within the repo management process.  Maybe make into an action that just gets triggered manually?

**Comment by ArielSAdamsNASA** [comment]
Updated to trigger workflow manually.

**Comment by skliper** [comment]
Sorry, I meant trigger the MISRA check as manual.  The normal static analysis should still be in the normal push/merge flow since we do need to enforce it.

**Comment by ArielSAdamsNASA** [comment]
> Sorry, I meant trigger the MISRA check as manual. The normal static analysis should still be in the normal push/merge flow since we do need to enforce it.

So have a separate workflow for the misra analysis that runs manually?

**Review by skliper — APPROVED** [review]

**Pull request merged**
