### PR TITLE
Fix #310,  No File Found Documentation Workflow

### LINKED ISSUE #310: No File Found for Documentation and Guides Workflow
**Checklist (Please check before submitting)**

* [x] I reviewed the [Contributing Guide](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md).
* [x] I performed a cursory search to see if the bug report is relevant, not redundant, nor in conflict with other tickets.

**Describe the bug**
The OSAL and cFE Users Guide PDF documentation are not generating due to errors in the workflow. 

**To Reproduce**
See https://github.com/nasa/cFS/runs/3107101587?check_suite_focus=true

**Expected behavior**
The OSAL and cFE Users Guide PDF documentation should generate and upload to gh-pages. 

**Code snips**
`./build/docs/users_guide/latex: No such file or directory`

**System observed on:**
GitHub Actions Workflows 

**Reporter Info**
Ariel Adams, ASRC Federal

### PR DESCRIPTION
**Pull request by ArielSAdamsNASA**
**Checklist (Please check before submitting)**

* [x] I reviewed the [Contributing Guide](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md).
* [ ] I signed and emailed the appropriate Contributor License agreement to GSFC-SoftwareRelease@mail.nasa.gov and copied cfs-program@lists.nasa.gov.

**Describe the contribution**
Fixes #310 
Workflow was failing due to files not persisting between jobs. Used cache action. 

**Testing performed**
Tested on fork: https://github.com/ArielSAdamsNASA/cFS-JSF-Rules/actions/runs/1057135024

**Expected behavior changes**
PDFs should generate. 

**Additional context**
PDFs will generate when push on main branch.

**Contributor Info - All information REQUIRED for consideration of pull request**
Ariel Adams, ASRC Federal

### CODE REVIEW

**Review by astrogeco — APPROVED** [review]

**Comment by astrogeco** [comment]
@ArielSAdams could you squash?

**Comment by ArielSAdamsNASA** [comment]
> @ArielSAdams could you squash?

Having issues trying to fix the conflicting files and squash them.

**Comment by astrogeco** [comment]
@ArielSAdamsNASA can you see if my fixes look right?
https://github.com/astrogeco/cFS/actions/runs/1057482277/workflow

**Comment by ArielSAdamsNASA** [comment]
> @ArielSAdamsNASA can you see if my fixes look right?
> https://github.com/astrogeco/cFS/actions/runs/1057482277/workflow

Looks good!

**Pull request merged**
