### PR TITLE
Integration Candidate: 2020-05-20

### LINKED ISSUE #88: Code style update - only inline empty functions
**Is your feature request related to a problem? Please describe.**
Complaints about single line functions being inline

**Describe the solution you'd like**
Don't.

**Describe alternatives you've considered**
Ignore complaints.

**Additional context**
None, whitespace.

**Requester Info**
Jacob Hageman - NASA/GSFC, per https://github.com/nasa/sample_lib/pull/23#pullrequestreview-416317282

### PR DESCRIPTION
**Pull request by astrogeco**
**Describe the contribution**

Combines:
1. nasa/psp#166
2. nasa/osal#482
3. nasa/cFS-GroundSystem#94
4. https://github.com/nasa/to_lab/pull/43
5. https://github.com/nasa/sample_lib/pull/24
6. https://github.com/nasa/sch_lab/pull/41
7. https://github.com/nasa/tblCRCTool/pull/18
8. https://github.com/nasa/elf2cfetbl/pull/44

And

Fix #88 

**Testing performed**
Bundle CI - https://travis-ci.com/github/nasa/cFS/builds/168824126

**Expected behavior changes**
See PRs for submodules above
PR #89 

**System(s) tested on**
Ubuntu: Bionic

**Additional context**
See PRs

**Contributor Info - All information REQUIRED for consideration of pull request**
Jacob Hageman, NASA-GSFC
See PRs for other contributors

### CODE REVIEW

**Comment by astrogeco** [comment]
@lbleier-GSFC can you help me out with some of the userguide doxygen errors showing up on Travis?

**Comment by astrogeco** [comment]
@skliper and @jphickey Unit test no. 52 is failing with OMIT_DEPRECATED

**Comment by jphickey** [comment]
> @skliper and @jphickey Unit test no. 52, osal-core-test, is hanging with OMIT_DEPRECATED=TRUE

I pulled the integration-candidate and re-ran locally and everything worked, so I'm hoping this was just some sort of Travis anomaly.  The other build was passing that test but then failing due to a doxygen warning.  I pushed a hotfix to correct that.

**Comment by jphickey** [comment]
This time around it is failing on `BUILDTYPE=release OMIT_DEPRECATED=false` combination.  Unfortunately I can't seem to make it fail locally for me.  Still looking into it... if anyone else is able to pull the IC and run it, would be helpful to get more data points to figure out what is the difference that makes this work/not work.

**Comment by jphickey** [comment]
OK - merge fix in bef86a7 may have resolved the issue with the osal-core-test.  (while I couldn't replicate the same issue, I did see a different issue when looking at my local logs, which was possibly related).

The next issue is regarding the startup script and is related to nasa/osal#461 and nasa/psp#163 ... right now we've got one without the other which is causing the problem. If we merge nasa/osal#461 should get fixed.

**Pull request merged**
