### PR TITLE
Integration Candidate 20200121

### PR DESCRIPTION
**Pull request by skliper**
**Describe the contribution**
Updated all branches to IC-20200121

**Testing performed**
1. Current CI passes
1. Enhanced CI in #40 passes debug/with deprecated elements testing

**Expected behavior changes**
See submodules

**System(s) tested on**
 - CI testing only

**Additional context**
N/A

**Code contibutions**
The cFS repository is provided to bundle the cFS Framework.  It is utilized for bundling submodules, continuous integration testing, and version management and does not contain any software.  Code contributions should be directed to the appropriate submodule.

**Contributor Info - All information REQUIRED for consideration of pull request**
Jacob Hageman - NASA/GSFC

### CODE REVIEW

**Comment by linayurkova** [comment]
Identified the same system issue.

**Comment by skliper** [comment]
> Identified the same system issue.

@linayurkova could you specify the matrix settings for the 2nd occurrence of this issue?

**Comment by linayurkova** [comment]
Matrix settings for the second occurrence:
 AMD64
 Compiler: gcc C
BUILDTYPE=release OMIT_DEPRECATED=true

**Comment by astrogeco** [comment]
Changes directly applied to master. Closing PR

**Pull request closed without merging**
